title: AICO HomeLINK
remote_theme: just-the-docs/just-the-docs

search_enabled: true
search:
  heading_level: 3

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/RogerSelwyn/AICO_HomeLINK" # the github URL for your repo
gh_edit_branch: "main" # the branch that your docs is served from
gh_edit_source: docs # the source that your files originate from
gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately
